#!/usr/bin/env python3
"""MITM server for reverse-engineering the arbigab bot.

Listens on :443 with a cert/key from /tmp/mitm/ (generated by setup.sh) and
routes by Host header:

  gabagool22.com                         → logs every request body
  gamma-api.polymarket.com               → /events stub
  clob.polymarket.com                    → /auth/api-key, /auth/derive-api-key,
                                           /data/orders, /order (signed order
                                           capture!), etc.
  ws-subscriptions-clob.polymarket.com   → /ws/market + /ws/user WebSocket
                                           handlers that speak just enough of
                                           the CLOB protocol to drive the bot
                                           all the way to a signed /order POST.

All request bodies / WS inbound messages are logged to stdout (redirect to a
file via `>> /tmp/mitm/capture.log`). Structured order captures are also
written to /tmp/mitm/order.json every time POST /order fires.

Usage:
    sudo python3 server.py
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import ssl
import sys
import time
import uuid
from typing import Any

from aiohttp import WSMsgType, web

CERT = "/tmp/mitm/srv.crt"
KEY = "/tmp/mitm/srv.key"
LOG_DIR = "/tmp/mitm"
ORDER_LOG = os.path.join(LOG_DIR, "order.json")
WS_LOG = os.path.join(LOG_DIR, "ws.log")

os.makedirs(LOG_DIR, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("mitm")


# --- stubbed JSON responses -------------------------------------------------

UP_TOKEN = "10000000000000000000000000000000000000000000000000000000000000001"
DOWN_TOKEN = "10000000000000000000000000000000000000000000000000000000000000002"
CONDITION_ID = "0x" + "aa" * 32


def gamma_events_stub() -> list[dict]:
    return [{
        "id": "stub-event",
        "slug": "stub",
        "title": "Stub event (MITM)",
        "active": True,
        "closed": False,
        "markets": [{
            "conditionId": CONDITION_ID,
            "question": "Stub market",
            "slug": "stub-market",
            "active": True,
            "closed": False,
            "endDate": "2099-01-01T00:00:00Z",
            "clobTokenIds": json.dumps([UP_TOKEN, DOWN_TOKEN]),
            "outcomes": json.dumps(["Up", "Down"]),
            "outcomePrices": json.dumps(["0.5", "0.5"]),
            "minimumOrderSize": "1",
            "minimumTickSize": "0.01",
            "negRisk": False,
        }],
    }]


def gamma_markets_slug_stub() -> dict:
    return gamma_events_stub()[0]["markets"][0]


def clob_auth_creds_stub() -> dict:
    return {
        "apiKey": "00000000-0000-0000-0000-000000000000",
        "secret": "c3R1YnN0dWJzdHVic3R1YnN0dWJzdHVic3R1YnN0dWJzdHVic3R1YnM=",
        "passphrase": "stubpassphrase",
        "api_key": "00000000-0000-0000-0000-000000000000",
    }


def clob_order_response_stub(body: dict) -> dict:
    oid = f"0x{uuid.uuid4().hex}"
    return {
        "success": True,
        "errorMsg": "",
        "orderId": oid,
        "orderID": oid,  # SDK rename: expects camelCase `orderID`
        "orderHashes": [oid],
        "transactionsHashes": [],
        "status": "live",
        "takingAmount": body.get("order", {}).get("takerAmount", "0"),
        "makingAmount": body.get("order", {}).get("makerAmount", "0"),
    }


# --- HTTP routing ----------------------------------------------------------

routes = web.RouteTableDef()


def _host(req: web.Request) -> str:
    return (req.headers.get("Host") or "").lower()


async def _log_body(req: web.Request, tag: str) -> bytes:
    body = await req.read()
    short = body[:4000].decode("utf-8", errors="replace")
    log.info("[%s] %s %s %s  body=%s", tag, req.method, _host(req), req.path, short)
    return body


@routes.route("*", "/{tail:.*}")
async def catchall(req: web.Request) -> web.Response:
    host = _host(req)
    path = req.path

    # ---- gabagool22.com ---------------------------------------------------
    if "gabagool22.com" in host:
        body = await _log_body(req, "PHONE-HOME")
        try:
            j = json.loads(body)
            if isinstance(j, dict):
                log.info("[PHONE-HOME] keys: %s", sorted(j.keys()))
        except Exception:
            pass
        return web.json_response({"ok": True})

    # ---- gamma-api.polymarket.com ----------------------------------------
    if "gamma-api.polymarket.com" in host:
        await _log_body(req, "GAMMA")
        if path.startswith("/events"):
            return web.json_response(gamma_events_stub())
        if path.startswith("/markets/slug/"):
            return web.json_response(gamma_markets_slug_stub())
        return web.json_response(gamma_events_stub())

    # ---- clob.polymarket.com ---------------------------------------------
    if "clob.polymarket.com" in host:
        body = await _log_body(req, "CLOB")
        if path.startswith("/auth/api-key") or path.startswith("/auth/derive-api-key"):
            return web.json_response(clob_auth_creds_stub())
        if path == "/order":
            try:
                j = json.loads(body) if body else {}
            except Exception:
                j = {}
            record = {
                "timestamp": time.time(),
                "headers": dict(req.headers),
                "body": j,
            }
            with open(ORDER_LOG, "a") as f:
                f.write(json.dumps(record) + "\n")
            log.info("[ORDER-CAPTURED] → %s", ORDER_LOG)
            return web.json_response(clob_order_response_stub(j if isinstance(j, dict) else {}))
        if path == "/orders":
            try:
                j = json.loads(body) if body else []
            except Exception:
                j = []
            record = {
                "timestamp": time.time(),
                "headers": dict(req.headers),
                "body": j,
            }
            with open(ORDER_LOG, "a") as f:
                f.write(json.dumps(record) + "\n")
            log.info("[ORDERS-CAPTURED] → %s (%d legs)", ORDER_LOG,
                     len(j) if isinstance(j, list) else 1)
            # Batch response: SDK expects a sequence of per-order responses.
            n = len(j) if isinstance(j, list) else 1
            return web.json_response(
                [clob_order_response_stub(item if isinstance(item, dict) else {}) for item in (j if isinstance(j, list) else [{}] * n)]
            )
        if path.startswith("/data/orders"):
            return web.json_response({"data": [], "next_cursor": "LTE="})
        if path.startswith("/data/positions"):
            return web.json_response([])
        if path.startswith("/fee-rate"):
            return web.json_response({"base_fee": 0, "maker_fee": 0, "taker_fee": 0})
        if path.startswith("/neg-risk"):
            return web.json_response({"neg_risk": False})
        if path.startswith("/tick-size"):
            return web.json_response({"minimum_tick_size": 0.01})
        return web.json_response({"ok": True})

    # ---- anything else ---------------------------------------------------
    await _log_body(req, "UNKNOWN")
    return web.json_response({"ok": True})


# --- WebSocket handlers ---------------------------------------------------

def book_snapshot(asset_id: str, bids: list[tuple[str, str]], asks: list[tuple[str, str]]) -> dict:
    return {
        "event_type": "book",
        "market": CONDITION_ID,
        "asset_id": asset_id,
        "timestamp": str(int(time.time() * 1000)),
        "hash": "0x" + "00" * 20,
        "bids": [{"price": p, "size": s} for p, s in bids],
        "asks": [{"price": p, "size": s} for p, s in asks],
    }


async def ws_log(direction: str, msg: Any) -> None:
    with open(WS_LOG, "a") as f:
        f.write(f"{time.strftime('%H:%M:%S')} {direction} {msg}\n")


async def market_ws(request: web.Request) -> web.WebSocketResponse:
    ws = web.WebSocketResponse()
    await ws.prepare(request)
    log.info("[WS-MARKET] client connected")
    await ws_log("CONN", request.headers.get("Host"))

    async def sender() -> None:
        # Wait a moment for subscription then push an arbitrage-triggering book.
        await asyncio.sleep(0.5)
        # Dutch Book fires when ask_up + ask_down < 1.0 - spread_threshold.
        # Default threshold 0.02 → need sum < 0.98. Serve asks at 0.45/0.50 → sum 0.95.
        snap_up = book_snapshot(UP_TOKEN,
                                bids=[("0.43", "500"), ("0.42", "1000")],
                                asks=[("0.45", "500"), ("0.46", "1000")])
        snap_down = book_snapshot(DOWN_TOKEN,
                                  bids=[("0.48", "500"), ("0.47", "1000")],
                                  asks=[("0.50", "500"), ("0.51", "1000")])
        payload = json.dumps([snap_up, snap_down])
        try:
            await ws.send_str(payload)
        except ConnectionResetError:
            return
        log.info("[WS-MARKET] sent book (asks 0.45+0.50=0.95, < 0.98 → dutch_book triggers)")
        await ws_log("SEND", payload[:300])
        while not ws.closed:
            await asyncio.sleep(10)
            try:
                await ws.ping()
            except ConnectionResetError:
                break

    send_task = asyncio.create_task(sender())
    try:
        async for msg in ws:
            if msg.type == WSMsgType.TEXT:
                log.info("[WS-MARKET] recv: %s", msg.data[:300])
                await ws_log("RECV", msg.data)
            elif msg.type == WSMsgType.ERROR:
                log.info("[WS-MARKET] error: %s", ws.exception())
                break
    finally:
        send_task.cancel()
        log.info("[WS-MARKET] client disconnected")
    return ws


async def user_ws(request: web.Request) -> web.WebSocketResponse:
    ws = web.WebSocketResponse()
    await ws.prepare(request)
    log.info("[WS-USER] client connected")
    await ws_log("USER-CONN", request.headers.get("Host"))
    try:
        async for msg in ws:
            if msg.type == WSMsgType.TEXT:
                log.info("[WS-USER] recv: %s", msg.data[:300])
                await ws_log("USER-RECV", msg.data)
            elif msg.type == WSMsgType.ERROR:
                break
    finally:
        log.info("[WS-USER] client disconnected")
    return ws


# --- combined app ---------------------------------------------------------

def make_app() -> web.Application:
    app = web.Application(client_max_size=1024 * 1024)
    app.router.add_get("/ws/market", market_ws)
    app.router.add_get("/ws/user", user_ws)
    app.add_routes(routes)
    return app


def main() -> int:
    ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_ctx.load_cert_chain(CERT, KEY)

    app = make_app()
    log.info("Starting MITM server on :443 with cert %s", CERT)
    log.info("Order captures → %s", ORDER_LOG)
    log.info("WS log → %s", WS_LOG)
    web.run_app(app, host="0.0.0.0", port=443, ssl_context=ssl_ctx, access_log=None)
    return 0


if __name__ == "__main__":
    sys.exit(main())
